### ISSUE TITLE
Lisence for materials ?

### ISSUE THREAD

**Issue by cerebrux** [iosifidis/stathis-marketing-materials#1]
What is the Lisence for the use of your materials ?

**Comment by iosifidis** [comment]
I don't own the licence of the logos, pictures etc. I used them only for creating my files.
The presentation files are under CC (didn't search the exact one).

**Comment by cerebrux** [comment]
Public content, should always have a clear license to preserve the rights of the creators (either yours or those who have been used as material).
Do you want me to propose a license ?

**Comment by iosifidis** [comment]
Sure.
